/*
 * This source file was generated by the Gradle 'init' task
 */
package passwordmanager;

import passwordmanager.cli.CommandlineInterface;

public class App {
    public static void main(String[] args) {
        new CommandlineInterface().start();
    }
}
